### ISSUE TITLE
pip check failing for nteract-scrapbook

### ISSUE THREAD

**Issue by xylar** [conda-forge/nteract-scrapbook-feedstock#7]
See https://github.com/conda-forge/apache-airflow-providers-papermill-feedstock/pull/1

Downstream packages that have nteract-scrapbook as a dependency are failing `pip check`

```
+ pip check
apache-airflow-providers-papermill 1.0.2 requires nteract-scrapbook, which is not installed.
Tests failed for apache-airflow-providers-papermill-1.0.2-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```
This is presumably because `nteract-scrapbook` is no longer a package on its own but rather just a metapackage that installs `scrapbook`.  But conda metapackages don't get detected by pip.

This is a problem that has come up in a few other cases, too (see also https://github.com/conda-forge/azure-keyvault-feedstock/issues/6).

**Comment by xylar** [comment]
For now, I'm going to solve this by patching the pypi package to rename the dependency `nteract-scrapbook` --> `scrapbook`.  Hopefully, Airflow developers will become aware of the rename and fix this.

**Comment by bollwyvl** [comment]
Yeah, we _just_ added this on #6. If it's going to cause issues, we can pull it. The pypi upstreams will just have to change their dependencies to move forward. I think the most hurtful one is probably `psycopg2-binary`.

**Comment by bollwyvl** [comment]
The admin request we denied, so i guess we're stuck with `nteract-feedstock !=0.5.0` until the issue is resolved upstream in pypi.
